export interface CustomIconOption {
  name: string;
  label: string;
  library?: 'Ionicons' | 'MaterialCommunityIcons';
}

export const CUSTOM_ICONS: CustomIconOption[] = [
  // General
  { name: 'star', label: 'Star' },
  { name: 'heart', label: 'Heart' },
  { name: 'flash', label: 'Flash' },
  { name: 'flame', label: 'Flame' },
  { name: 'diamond', label: 'Diamond' },
  { name: 'trophy', label: 'Trophy' },
  { name: 'ribbon', label: 'Ribbon' },
  { name: 'gift', label: 'Gift' },
  // Tech
  { name: 'phone-portrait', label: 'Phone' },
  { name: 'laptop', label: 'Laptop' },
  { name: 'desktop', label: 'Desktop' },
  { name: 'tablet-portrait', label: 'Tablet' },
  { name: 'wifi', label: 'WiFi' },
  { name: 'cloud', label: 'Cloud' },
  { name: 'code-slash', label: 'Code' },
  { name: 'hardware-chip', label: 'Chip' },
  // Media
  { name: 'musical-notes', label: 'Music' },
  { name: 'film', label: 'Film' },
  { name: 'tv', label: 'TV' },
  { name: 'camera', label: 'Camera' },
  { name: 'image', label: 'Photo' },
  { name: 'mic', label: 'Mic' },
  { name: 'headset', label: 'Headset' },
  { name: 'radio', label: 'Radio' },
  { name: 'videocam', label: 'Video' },
  // Work & Productivity
  { name: 'briefcase', label: 'Work' },
  { name: 'document-text', label: 'Document' },
  { name: 'mail', label: 'Mail' },
  { name: 'chatbubbles', label: 'Chat' },
  { name: 'calendar', label: 'Calendar' },
  { name: 'clipboard', label: 'Clipboard' },
  { name: 'bar-chart', label: 'Stats' },
  { name: 'folder', label: 'Folder' },
  { name: 'print', label: 'Print' },
  { name: 'pencil', label: 'Edit' },
  // Lifestyle
  { name: 'bicycle', label: 'Cycling' },
  { name: 'football', label: 'Sports' },
  { name: 'fitness', label: 'Fitness' },
  { name: 'leaf', label: 'Nature' },
  { name: 'restaurant', label: 'Food' },
  { name: 'cafe', label: 'Coffee' },
  { name: 'car', label: 'Car' },
  { name: 'home', label: 'Home' },
  { name: 'book', label: 'Book' },
  { name: 'school', label: 'School' },
  { name: 'medkit', label: 'Health' },
  { name: 'game-controller', label: 'Gaming' },
  { name: 'airplane', label: 'Travel' },
  { name: 'bed', label: 'Sleep' },
  // Shopping & Finance
  { name: 'cart', label: 'Shop' },
  { name: 'wallet', label: 'Wallet' },
  { name: 'pricetag', label: 'Price' },
  { name: 'shield', label: 'Shield' },
  { name: 'lock-closed', label: 'Lock' },
  { name: 'color-palette', label: 'Design' },
  { name: 'sparkles', label: 'AI' },
  { name: 'language', label: 'Language' },
];

export const BRAND_ICONS: CustomIconOption[] = [
  { name: 'netflix', label: 'Netflix', library: 'MaterialCommunityIcons' },
  { name: 'spotify', label: 'Spotify', library: 'MaterialCommunityIcons' },
  { name: 'youtube', label: 'YouTube', library: 'MaterialCommunityIcons' },
  { name: 'apple', label: 'Apple', library: 'MaterialCommunityIcons' },
  { name: 'google', label: 'Google', library: 'MaterialCommunityIcons' },
  { name: 'microsoft', label: 'Microsoft', library: 'MaterialCommunityIcons' },
  { name: 'microsoft-office', label: 'Office', library: 'MaterialCommunityIcons' },
  { name: 'slack', label: 'Slack', library: 'MaterialCommunityIcons' },
  { name: 'dropbox', label: 'Dropbox', library: 'MaterialCommunityIcons' },
  { name: 'twitch', label: 'Twitch', library: 'MaterialCommunityIcons' },
  { name: 'linkedin', label: 'LinkedIn', library: 'MaterialCommunityIcons' },
  { name: 'sony-playstation', label: 'PlayStation', library: 'MaterialCommunityIcons' },
  { name: 'microsoft-xbox', label: 'Xbox', library: 'MaterialCommunityIcons' },
  { name: 'nintendo-switch', label: 'Nintendo', library: 'MaterialCommunityIcons' },
  { name: 'steam', label: 'Steam', library: 'MaterialCommunityIcons' },
  { name: 'whatsapp', label: 'WhatsApp', library: 'MaterialCommunityIcons' },
  { name: 'skype', label: 'Skype', library: 'MaterialCommunityIcons' },
  { name: 'instagram', label: 'Instagram', library: 'MaterialCommunityIcons' },
  { name: 'facebook', label: 'Facebook', library: 'MaterialCommunityIcons' },
  { name: 'twitter', label: 'Twitter', library: 'MaterialCommunityIcons' },
  { name: 'github', label: 'GitHub', library: 'MaterialCommunityIcons' },
  { name: 'reddit', label: 'Reddit', library: 'MaterialCommunityIcons' },
];
